### ISSUE TITLE
Custom rule added ?

### ISSUE THREAD

**Issue by n30gupta** [Shopify/kubeaudit#375]
Hi,

Can we add any custom rules once installing kubeaduit.

**Comment by genevieveluyt** [comment]
Hi @n30gupta, if you import kubeaudit as a Go package rather than as a CLI then yes you can implement custom rules. There is an [example](https://pkg.go.dev/github.com/Shopify/kubeaudit#example-package-CustomAuditor) in the docs. If you're hoping to use the CLI you would probably need to clone/fork the repo.

Depending on the custom rule, it may be possible to add a more generalized version of the rule to the kubeaudit codebase and then you can use configuration to customize it to your specific needs. For example, if you're hoping to have kubeaudit find kubernetes resources with a specific label, we could add a label auditor, where the actual label value(s) to audit for could be supplied via configuration.

If you're able to share the custom rule you have in mind I might be able to provide better advice.
